#
# (C) Copyright 2003-2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
# (C) Copyright 2009
# Yanhua, Lemote Software Engineering, yanh@lemote.com.
# (C) Copyright 2015
# Hsiang Kao, Hefei University of Technology, 0xe0e1e@gmail.com
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= yl8089.o flash.o bonito-pci.o cs5536_vsm.o cs5536.o
obj-y	+= lowlevel_init.o
