#
# (C) Copyright 2003
# Wolfgang Denk, DENX Software Engineering, <wd@denx.de>
# (C) Copyright 2015
# Hsiang Kao, Hefei University of Technology, <0xe0e1e@gmail.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y = cache.o
obj-y += cpu.o io.o
